version: '2.1'
services:
  keycloak:
    image:  quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    command: [ "-Djboss.socket.binding.port-offset=0" ]
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    ports:
      - "8082:8080"
  app:
    build: ./
    container_name: "key"
    ports:
      - "8080:8080"
